package org.henry.wx_account.dao;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.henry.wx_account.bean.Account;
import org.henry.wx_account.bean.AccountExample;
import org.henry.wx_account.bean.QueryAccount;

public interface AccountMapper {
	
	
	
	
	List<Account> getAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_account
     *
     * @mbggenerated Wed Sep 20 15:27:42 CST 2017
     */
    int updateByPrimaryKey(Account record);
    List<Account> queryByUserId(String openid);
	List<Account> queryBy(QueryAccount q);
	
}